const productsData = [
  {
    "id": "irs2092-class-d-amplifier",
    "title": "IRS2092 High Power Class D Amplifier Board with Speaker Protection",
    "price": 2950,
    "stock": 9,
    "category": "audio",
    "description": "Unleash exhilarating audio with the IRS2092 High Power Class D Amplifier Board! Delivering immense power and pristine clarity through efficient Class D technology, it's perfect for your next high-fidelity project. Plus, robust speaker protection ensures your valuable drivers are always safe.\n\n\n",
    "condition": "Brand New",
    "features": [
      "Main chip: IRS2092 / IRS2092S",
      "Gain: 18.9×",
      "25.2×",
      "or 30.2× depending on board version",
      "Input sensitivity: approx. 1.48V–1.49V",
      "Working voltage: typically ±40V–±77V",
      "some versions rated up to ±85V",
      "SNR: more than 96dB (low-noise input stage)",
      "Protection: speaker protection circuits included",
      "Additional protection: short-circuit",
      "over-current",
      "over-temperature",
      "under-voltage",
      "over-voltage\nSpeaker support: 10″",
      "12″",
      "15″",
      "18″ when matched correctly with power supply and speaker rating"
    ],
    "buyingDelivery": [
      "Buying & delivery\nCall or WhatsApp to confirm availability",
      "Cash on delivery available",
      "Delivery fee depends on item weight and location"
    ],
    "tags": [
      "IRS2092",
      "Class D amplifier",
      "High power audio",
      "Speaker protection",
      "Audio amplifier board",
      "Digital amplifier",
      "DIY audio"
    ],
    "image": "images/products/media__1__1777089796499.jpeg",
    "isDeleted": false,
    "createdAt": "2026-04-28T16:53:04.653Z",
    "updatedAt": "2026-04-28T17:31:30.968Z",
    "meta": "Audio electronics · High power Class D amp",
    "link": "product.html?id=irs2092-class-d-amplifier",
    "svg": "",
    "images": {},
    "badge": null
  },
  {
    "id": "wifi-smart-power-meter-with-40a-switch",
    "title": "WiFi Smart Power Meter with 40A Switch",
    "price": 6990,
    "stock": 1,
    "category": "modules",
    "description": "Wi-Fi smart power meter with 40A built-in switch. Supports Smart Life, Tuya Smart, Google Home, and Amazon Alexa. Monitors voltage, current, power, frequency, energy usage, and more.",
    "condition": "Brand New",
    "features": [
      "Brand: SZDQ",
      "Type: WiFi Smart Power Meter with built-in switch",
      "Rated switch capacity: 40A",
      "App support: Smart Life",
      "Tuya Smart",
      "Voice assistant: Google Home",
      "Amazon Alexa",
      "Display: electricity usage",
      "power factor",
      "voltage",
      "current",
      "power",
      "frequency",
      "temperature",
      "alarm",
      "on/off status",
      "Control: WiFi app + manual buttons on device",
      "Mounting type: DIN rail",
      "Use: power line control",
      "electricity monitoring",
      "smart home automation"
    ],
    "buyingDelivery": [
      "Call or WhatsApp to confirm availability",
      "Cash on delivery available",
      "Delivery fee depends on item weight and location"
    ],
    "tags": [],
    "image": "images/products/dji_neo_drone_with_remote_camera_fly_more_combo_5_1777049726873.jpg",
    "isDeleted": false,
    "createdAt": "2026-04-28T16:53:04.649Z",
    "updatedAt": "2026-04-28T16:53:04.649Z",
    "meta": "Smart home · Energy monitoring",
    "link": "product.html?id=wifi-smart-power-meter-with-40a-switch",
    "svg": "",
    "images": {},
    "badge": "Smart home · Energy monitoring"
  },
  {
    "id": "dji-neo-6-in-1-filter-pack",
    "title": "DJI Neo 6-in-1 Filter Pack",
    "price": null,
    "stock": 1,
    "category": "drone",
    "description": "Selling a brand new 6-in-1 filter pack for DJI Neo. Includes ND8, ND16, ND32, ND64, CPL, and MCUV filters. Neat set, unused, and ready to use.",
    "condition": "Brand New",
    "features": [
      "Pack includes: ND8",
      "ND16",
      "ND32",
      "ND64",
      "CPL",
      "MCUV (6 filters total)",
      "Designed for DJI Neo drone camera",
      "Condition: brand new and unused",
      "Helps improve video and photo quality in different lighting conditions",
      "Neat set",
      "ready to use straight from the pack"
    ],
    "buyingDelivery": [
      "Call or WhatsApp to confirm availability",
      "Location: Negombo",
      "Kochchikade",
      "Pickup or delivery can be discussed",
      "Cash on delivery available"
    ],
    "tags": [],
    "image": "images/products/dji_neo_drone_with_remote_camera_fly_more_combo_5_1777049546959.jpg",
    "isDeleted": false,
    "createdAt": "2026-04-28T16:53:04.644Z",
    "updatedAt": "2026-04-28T16:53:04.644Z",
    "meta": "ND8/16/32/64 · CPL · MCUV",
    "link": "product.html?id=dji-neo-6-in-1-filter-pack",
    "svg": "",
    "images": {},
    "badge": "DJI"
  },
  {
    "id": "mp1584-buck-converter",
    "title": "DC Step Down Mini Buck Converter MP1584",
    "price": 250,
    "stock": 1,
    "category": "modules",
    "description": "Adjustable DC-DC step down converter. Input 4.75–23V, output 1–17V. Compact, high efficiency.",
    "condition": "Brand new",
    "features": [],
    "buyingDelivery": [],
    "tags": [],
    "image": "",
    "isDeleted": false,
    "createdAt": "2026-04-28T16:53:04.641Z",
    "updatedAt": "2026-04-28T16:56:58.101Z",
    "meta": "Up to 3A · 96% eff.",
    "link": "products/mp1584-buck-converter.html",
    "svg": "<rect x=\"130\" y=\"113\" width=\"160\" height=\"90\" rx=\"6\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><rect x=\"165\" y=\"138\" width=\"90\" height=\"40\" rx=\"4\" fill=\"currentColor\" opacity=\"0.10\"/><text x=\"210\" y=\"161\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.68\" font-family=\"sans-serif\" font-weight=\"bold\">MP1584</text><circle cx=\"312\" cy=\"158\" r=\"18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.42\"/><text x=\"312\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"8\" fill=\"currentColor\" opacity=\"0.55\" font-family=\"sans-serif\">ADJ</text><text x=\"210\" y=\"252\" text-anchor=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.42\" font-family=\"sans-serif\">4.75–23V → 1–17V · 96% eff.</text>",
    "images": null,
    "badge": null
  },
  {
    "id": "pam8610-amplifier",
    "title": "PAM8610 Stereo Amplifier 2×10W/2×15W",
    "price": 400,
    "stock": 5,
    "category": "audio",
    "description": "Class D stereo amp board. 2×10W at 8Ω or 2×15W at 4Ω. Low EMI, mute control, 7–15V supply.",
    "condition": "Brand new",
    "features": [],
    "buyingDelivery": [],
    "tags": [],
    "image": "",
    "isDeleted": false,
    "createdAt": "2026-04-28T16:53:04.638Z",
    "updatedAt": "2026-04-28T16:57:29.775Z",
    "meta": "12V · Class D",
    "link": "products/pam8610-amplifier.html",
    "svg": "<rect x=\"80\" y=\"93\" width=\"260\" height=\"130\" rx=\"8\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><rect x=\"155\" y=\"123\" width=\"110\" height=\"70\" rx=\"4\" fill=\"currentColor\" opacity=\"0.10\"/><text x=\"210\" y=\"161\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"13\" fill=\"currentColor\" opacity=\"0.68\" font-family=\"sans-serif\" font-weight=\"bold\">PAM8610</text><text x=\"210\" y=\"262\" text-anchor=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.42\" font-family=\"sans-serif\">2×10W (8Ω) · 2×15W (4Ω)</text>",
    "images": null,
    "badge": null
  },
  {
    "id": "vhm-314-bluetooth",
    "title": "VHM-314 Bluetooth 5.0 Audio Receiver",
    "price": null,
    "stock": 0,
    "category": "audio",
    "description": "Wireless audio receiver module. Converts any speaker system to Bluetooth. 15m+ range, A2DP / AVRCP.",
    "condition": "Brand new",
    "features": [],
    "buyingDelivery": [],
    "tags": [],
    "image": null,
    "isDeleted": false,
    "createdAt": "2026-04-28T16:53:04.635Z",
    "updatedAt": "2026-04-28T16:53:04.635Z",
    "meta": "BT 5.0 · Stereo",
    "link": "products/vhm-314-bluetooth.html",
    "svg": "<rect x=\"100\" y=\"88\" width=\"220\" height=\"140\" rx=\"10\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><path d=\"M200 138 l20 20 -20 20 m20-40 l0 80\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" opacity=\"0.60\"/><path d=\"M200 158 l-12-12 m12 12 l-12 12\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" opacity=\"0.38\"/><text x=\"210\" y=\"268\" text-anchor=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.42\" font-family=\"sans-serif\">BT 5.0 · A2DP · AVRCP</text>",
    "images": null,
    "badge": null
  },
  {
    "id": "xh-a901-preamp",
    "title": "XH-A901 NE5532 Tone Control PreAmp",
    "price": 200,
    "stock": 3,
    "category": "audio",
    "description": "Dual NE5532 preamp board. Bass, mid, treble, volume controls. DIY amplifier and home audio.",
    "condition": "Brand new",
    "features": [],
    "buyingDelivery": [],
    "tags": [],
    "image": "",
    "isDeleted": false,
    "createdAt": "2026-04-28T16:53:04.617Z",
    "updatedAt": "2026-04-28T16:53:04.617Z",
    "meta": "2ch Stereo · 12–24V",
    "link": "products/xh-a901-preamp.html",
    "svg": "<rect x=\"70\" y=\"108\" width=\"280\" height=\"100\" rx=\"8\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><circle cx=\"140\" cy=\"158\" r=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.50\"/><circle cx=\"210\" cy=\"158\" r=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.50\"/><circle cx=\"280\" cy=\"158\" r=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.50\"/><text x=\"140\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"9\" fill=\"currentColor\" opacity=\"0.60\" font-family=\"sans-serif\">BASS</text><text x=\"210\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"9\" fill=\"currentColor\" opacity=\"0.60\" font-family=\"sans-serif\">MID</text><text x=\"280\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"9\" fill=\"currentColor\" opacity=\"0.60\" font-family=\"sans-serif\">TRB</text>",
    "images": null,
    "badge": null
  },
  {
    "id": "4",
    "title": "psu",
    "price": 250,
    "stock": 1,
    "category": "audio",
    "description": "this is psu",
    "condition": "",
    "features": [],
    "buyingDelivery": [],
    "tags": [],
    "image": "",
    "isDeleted": false,
    "createdAt": "2026-04-28T15:48:26.432Z",
    "updatedAt": "2026-04-28T16:47:49.527Z",
    "meta": null,
    "link": null,
    "svg": null,
    "images": null,
    "badge": null
  }
];
