const productsData = [
  {
    "id": "dji-neo-propellers",
    "title": "DJI Neo Propellers",
    "price": "1850",
    "category": "drone",
    "condition": "New",
    "description": "Genuine spare replacement propellers for DJI Neo. Unused, original packaging.",
    "image": "images/products/dji-neo-propellers/cover.jpg",
    "specs": [],
    "features": [],
    "meta": "",
    "images": [],
    "buyingDelivery": [],
    "svg": "",
    "link": "product.html?id=dji-neo-propellers"
  },
  {
    "id": "xh-a901-preamp",
    "title": "XH-A901 NE5532 Tone Control PreAmp",
    "category": "audio",
    "condition": "Brand new",
    "meta": "2ch Stereo · 12–24V",
    "description": "Dual NE5532 preamp board. Bass, mid, treble, volume controls. DIY amplifier and home audio.",
    "price": "Contact for price",
    "link": "products/xh-a901-preamp.html",
    "image": null,
    "svg": "<rect x=\"70\" y=\"108\" width=\"280\" height=\"100\" rx=\"8\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><circle cx=\"140\" cy=\"158\" r=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.50\"/><circle cx=\"210\" cy=\"158\" r=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.50\"/><circle cx=\"280\" cy=\"158\" r=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.50\"/><text x=\"140\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"9\" fill=\"currentColor\" opacity=\"0.60\" font-family=\"sans-serif\">BASS</text><text x=\"210\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"9\" fill=\"currentColor\" opacity=\"0.60\" font-family=\"sans-serif\">MID</text><text x=\"280\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"9\" fill=\"currentColor\" opacity=\"0.60\" font-family=\"sans-serif\">TRB</text>"
  },
  {
    "id": "pam8403-amplifier",
    "title": "PAM8403 Stereo Amplifier 3W+3W",
    "category": "audio",
    "condition": "Brand new",
    "meta": "5V · Class D",
    "description": "Compact Class D amp, 3W+3W at 5V. USB power, short-circuit protection. DIY speakers and Bluetooth builds.",
    "price": "Contact for price",
    "link": "products/pam8403-amplifier.html",
    "image": null,
    "svg": "<rect x=\"110\" y=\"103\" width=\"200\" height=\"110\" rx=\"8\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><rect x=\"170\" y=\"133\" width=\"80\" height=\"50\" rx=\"4\" fill=\"currentColor\" opacity=\"0.10\"/><text x=\"210\" y=\"161\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.68\" font-family=\"sans-serif\" font-weight=\"bold\">PAM8403</text><text x=\"210\" y=\"246\" text-anchor=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.42\" font-family=\"sans-serif\">3W+3W · 5V · Class D</text>"
  },
  {
    "id": "vhm-314-bluetooth",
    "title": "VHM-314 Bluetooth 5.0 Audio Receiver",
    "category": "audio",
    "condition": "Brand new",
    "meta": "BT 5.0 · Stereo",
    "description": "Wireless audio receiver module. Converts any speaker system to Bluetooth. 15m+ range, A2DP / AVRCP.",
    "price": "Contact for price",
    "link": "products/vhm-314-bluetooth.html",
    "image": null,
    "svg": "<rect x=\"100\" y=\"88\" width=\"220\" height=\"140\" rx=\"10\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><path d=\"M200 138 l20 20 -20 20 m20-40 l0 80\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" opacity=\"0.60\"/><path d=\"M200 158 l-12-12 m12 12 l-12 12\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" opacity=\"0.38\"/><text x=\"210\" y=\"268\" text-anchor=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.42\" font-family=\"sans-serif\">BT 5.0 · A2DP · AVRCP</text>"
  },
  {
    "id": "pam8610-amplifier",
    "title": "PAM8610 Stereo Amplifier 2×10W/2×15W",
    "category": "audio",
    "condition": "Brand new",
    "meta": "12V · Class D",
    "description": "Class D stereo amp board. 2×10W at 8Ω or 2×15W at 4Ω. Low EMI, mute control, 7–15V supply.",
    "price": "Contact for price",
    "link": "products/pam8610-amplifier.html",
    "image": null,
    "svg": "<rect x=\"80\" y=\"93\" width=\"260\" height=\"130\" rx=\"8\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><rect x=\"155\" y=\"123\" width=\"110\" height=\"70\" rx=\"4\" fill=\"currentColor\" opacity=\"0.10\"/><text x=\"210\" y=\"161\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"13\" fill=\"currentColor\" opacity=\"0.68\" font-family=\"sans-serif\" font-weight=\"bold\">PAM8610</text><text x=\"210\" y=\"262\" text-anchor=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.42\" font-family=\"sans-serif\">2×10W (8Ω) · 2×15W (4Ω)</text>"
  },
  {
    "id": "mp1584-buck-converter",
    "title": "DC Step Down Mini Buck Converter MP1584",
    "category": "modules",
    "condition": "Brand new",
    "meta": "Up to 3A · 96% eff.",
    "description": "Adjustable DC-DC step down converter. Input 4.75–23V, output 1–17V. Compact, high efficiency.",
    "price": "Rs. 250",
    "link": "products/mp1584-buck-converter.html",
    "image": null,
    "svg": "<rect x=\"130\" y=\"113\" width=\"160\" height=\"90\" rx=\"6\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><rect x=\"165\" y=\"138\" width=\"90\" height=\"40\" rx=\"4\" fill=\"currentColor\" opacity=\"0.10\"/><text x=\"210\" y=\"161\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.68\" font-family=\"sans-serif\" font-weight=\"bold\">MP1584</text><circle cx=\"312\" cy=\"158\" r=\"18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.42\"/><text x=\"312\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"8\" fill=\"currentColor\" opacity=\"0.55\" font-family=\"sans-serif\">ADJ</text><text x=\"210\" y=\"252\" text-anchor=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.42\" font-family=\"sans-serif\">4.75–23V → 1–17V · 96% eff.</text>"
  },
  {
    "id": "wireless-microphone-set",
    "title": "Wireless Microphone Set (2 Mics + Receiver)",
    "category": "audio",
    "condition": "Brand new",
    "meta": "Dual mic · Receiver",
    "description": "2 wireless handheld mics with receiver circuit. Karaoke, PA, stage, meetings, church, events.",
    "price": "Rs. 5,450",
    "link": "products/wireless-microphone-set.html",
    "image": null,
    "svg": "<rect x=\"130\" y=\"68\" width=\"40\" height=\"80\" rx=\"20\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\" opacity=\"0.55\"/><line x1=\"150\" y1=\"148\" x2=\"150\" y2=\"188\" stroke=\"currentColor\" stroke-width=\"2.2\" opacity=\"0.45\"/><line x1=\"130\" y1=\"188\" x2=\"170\" y2=\"188\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.40\"/><rect x=\"250\" y=\"68\" width=\"40\" height=\"80\" rx=\"20\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.2\" opacity=\"0.55\"/><line x1=\"270\" y1=\"148\" x2=\"270\" y2=\"188\" stroke=\"currentColor\" stroke-width=\"2.2\" opacity=\"0.45\"/><line x1=\"250\" y1=\"188\" x2=\"290\" y2=\"188\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.40\"/><rect x=\"140\" y=\"218\" width=\"140\" height=\"46\" rx=\"8\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" opacity=\"0.45\"/><text x=\"210\" y=\"245\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"10\" fill=\"currentColor\" opacity=\"0.55\" font-family=\"sans-serif\">Receiver Circuit</text>"
  },
  {
    "id": "irs2092-class-d-amplifier",
    "title": "IRS2092 High Power Class D Amplifier",
    "category": "audio",
    "condition": "Brand new",
    "meta": "Sub / PA · 10–18″",
    "description": "IRS2092 Class D amp with speaker protection. Subwoofer, PA, bass bin builds. Full multi-protection.",
    "price": "Contact for price",
    "link": "products/irs2092-class-d-amplifier.html",
    "image": null,
    "svg": "<rect x=\"55\" y=\"78\" width=\"310\" height=\"160\" rx=\"10\" fill=\"none\" stroke=\"currentColor\" opacity=\"0.45\"/><rect x=\"155\" y=\"118\" width=\"110\" height=\"80\" rx=\"6\" fill=\"currentColor\" opacity=\"0.10\"/><text x=\"210\" y=\"162\" text-anchor=\"middle\" dominant-baseline=\"middle\" font-size=\"13\" fill=\"currentColor\" opacity=\"0.68\" font-family=\"sans-serif\" font-weight=\"bold\">IRS2092</text><rect x=\"65\" y=\"88\" width=\"12\" height=\"140\" rx=\"2\" fill=\"currentColor\" opacity=\"0.12\"/><rect x=\"82\" y=\"88\" width=\"12\" height=\"140\" rx=\"2\" fill=\"currentColor\" opacity=\"0.12\"/><rect x=\"99\" y=\"88\" width=\"12\" height=\"140\" rx=\"2\" fill=\"currentColor\" opacity=\"0.12\"/><text x=\"210\" y=\"278\" text-anchor=\"middle\" font-size=\"11\" fill=\"currentColor\" opacity=\"0.42\" font-family=\"sans-serif\">High Power · Sub / PA · 10–18″</text>"
  },
  {
    "id": "test1",
    "title": "testTitle",
    "price": "Rs. 6,99",
    "category": "drone",
    "condition": "Brand New",
    "meta": "meta info",
    "description": "this is disceptation ",
    "image": "images/products/dji_neo_drone_with_remote_camera_fly_more_combo_5_1777048699435.jpg",
    "images": [
      "images/products/hq720_1777048699437.jpg"
    ],
    "features": [
      "Feature 1"
    ],
    "buyingDelivery": [
      "free",
      "one month cehcking"
    ],
    "svg": "",
    "link": "product.html?id=test1",
    "badge": "sele badge "
  },
  {
    "id": "dji-neo-6-in-1-filter-pack",
    "title": "DJI Neo 6-in-1 Filter Pack",
    "price": "Rs. 6,950",
    "category": "drone",
    "condition": "Brand New",
    "meta": "ND8/16/32/64 · CPL · MCUV",
    "description": "Selling a brand new 6-in-1 filter pack for DJI Neo. Includes ND8, ND16, ND32, ND64, CPL, and MCUV filters. Neat set, unused, and ready to use.",
    "image": "images/products/dji_neo_drone_with_remote_camera_fly_more_combo_5_1777049546959.jpg",
    "images": [],
    "features": [
      "Pack includes: ND8",
      "ND16",
      "ND32",
      "ND64",
      "CPL",
      "MCUV (6 filters total)",
      "Designed for DJI Neo drone camera",
      "Condition: brand new and unused",
      "Helps improve video and photo quality in different lighting conditions",
      "Neat set",
      "ready to use straight from the pack"
    ],
    "buyingDelivery": [
      "Call or WhatsApp to confirm availability",
      "Location: Negombo",
      "Kochchikade",
      "Pickup or delivery can be discussed",
      "Cash on delivery available"
    ],
    "svg": "",
    "link": "product.html?id=dji-neo-6-in-1-filter-pack",
    "badge": "DJI"
  },
  {
    "id": "wifi-smart-power-meter-with-40a-switch",
    "title": "WiFi Smart Power Meter with 40A Switch",
    "price": "LKR:6990",
    "category": "modules",
    "condition": "Brand New",
    "meta": "Smart home · Energy monitoring",
    "description": "Wi-Fi smart power meter with 40A built-in switch. Supports Smart Life, Tuya Smart, Google Home, and Amazon Alexa. Monitors voltage, current, power, frequency, energy usage, and more.",
    "image": "images/products/dji_neo_drone_with_remote_camera_fly_more_combo_5_1777049726873.jpg",
    "images": [],
    "features": [
      "Brand: SZDQ",
      "Type: WiFi Smart Power Meter with built-in switch",
      "Rated switch capacity: 40A",
      "App support: Smart Life",
      "Tuya Smart",
      "Voice assistant: Google Home",
      "Amazon Alexa",
      "Display: electricity usage",
      "power factor",
      "voltage",
      "current",
      "power",
      "frequency",
      "temperature",
      "alarm",
      "on/off status",
      "Control: WiFi app + manual buttons on device",
      "Mounting type: DIN rail",
      "Use: power line control",
      "electricity monitoring",
      "smart home automation"
    ],
    "buyingDelivery": [
      "Call or WhatsApp to confirm availability",
      "Cash on delivery available",
      "Delivery fee depends on item weight and location"
    ],
    "svg": "",
    "link": "product.html?id=wifi-smart-power-meter-with-40a-switch",
    "badge": "Smart home · Energy monitoring"
  }
];
